Add missing include file
Compiling on Linux/i586 I get these warnings:
nss_db/db-initgroups.c:60:3: warning: implicit declaration of function
'strlen' [-Wimplicit-function-declaration]
nss_db/db-initgroups.c:74:7: warning: implicit declaration of function
'strncmp' [-Wimplicit-function-declaration]

Fixed with inclusion of <string.h>
(cherry picked from commit 2c040eff839ff8c2b1b1c3ab0f6cbb30976ce87a)

Conflicts:

	ChangeLog